import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="w-full py-8 mt-12 bg-anime-card backdrop-blur-sm border-t border-anime-accent/20">
      <div className="max-w-4xl mx-auto text-center px-4">
        <p className="text-anime-text/80 font-medium">
          Made with <span className="text-anime-accent inline-block animate-pulse">❤</span> and Passion!
        </p>
        <p className="text-sm text-anime-text/60 mt-2">
          © {new Date().getFullYear()} PangYan’s World content generated by PangYan.
        </p>
        <div className="flex justify-center gap-4 mt-4">
          {['Twitter', 'Pixiv', 'Github'].map((social) => (
            <button key={social} className="text-sm font-bold text-anime-secondary hover:text-anime-accent transition-colors">
              {social}
            </button>
          ))}
        </div>
      </div>
    </footer>
  );
};

export default Footer;